version: '3.7'
services:
  factoring_app:
    container_name: factoring_app
    hostname: factoring.local
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - factoring_db
    volumes:
      - ./factoring:/var/www/html/
    restart: on-failure:5
    ports:
      - 8001:80
    links:
      - factoring_db:mysql.local

  factoring_db:
    container_name: factoring_db
    hostname: mysql.local
    image: mysql:5.7
    #command: --default-authentication-plugin=mysql_native_password
    restart: always  
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=factoring
      - MYSQL_USER=devuser
      - MYSQL_PASSWORD=devpass
    ports:
      - 6033:3306
